db.url=jdbc:postgresql://localhost:5432/test_postgre
db.login=postgres
db.password=4sfl8gpassword

# Disable Vaadin dev server and file watcher threads when running inside the servlet container
vaadin.disable.dev.server=true