CREATE TABLE IF NOT EXISTS users(
	user_id SERIAL NOT NULL PRIMARY KEY,
	factory_type VARCHAR(8) NOT NULL DEFAULT 'array',
	login VARCHAR(32) NOT NULL,
	password VARCHAR(256) NOT NULL,
	role VARCHAR(8) NOT NULL DEFAULT 'user'
);